### ISSUE TITLE
KIOXIA-EXCERIA PLUS G2 SSD is not supported.

### ISSUE THREAD

**Issue by WanpengQian** [007revad/Synology_HDD_db#169]
Hi, I add two of these SSDs to DS1821+, and run the script. the output is

```
Synology_HDD_db v3.2.68
DS1821+ DSM 7.2.1-69057-3 
StorageManager 1.0.0-0017

Using options: -nr --showedits
Running from: /volume1/Synology_HDD_db-3.2.68/syno_hdd_db.sh

WARNING{OFF} No vendor found for id 0x1e0f
Contact 007revad to get your drive added.

WARNING{OFF} No vendor found for id 0x1e0f
Contact 007revad to get your drive added.

HDD/SSD models found: 1
MN06ACA10T,0603

M.2 drive models found: 2
KIOXIA-EXCERIA PLUS G2 SSD,ECFA11.3
KIOXIA-EXCERIA PLUS G2 SSD,ECFA13.3

No M.2 PCIe cards found

No Expansion Units found

MN06ACA10T already exists in ds1821+_host_v7.db
Added KIOXIA-EXCERIA PLUS G2 SSD to ds1821+_host_v7.db
Updated KIOXIA-EXCERIA PLUS G2 SSD to ds1821+_host_v7.db

Backed up synoinfo.conf

Support disk compatibility already enabled.

Disabled support memory compatibility.

Max memory already set to 32 GB.

NVMe support already enabled.

M.2 volume support already enabled.
```

after reboot. it shows

![Snipaste_2023-12-13_18-46-40](https://github.com/007revad/Synology_HDD_db/assets/6359418/8b164fed-eb9b-4038-8f99-2288ada2e8a4)

```
root@DNAS:~# nvme id-ctrl /dev/nvme0n1
NVME Identify Controller:
vid     : 0x1e0f
ssvid   : 0x1e0f
sn      : *******************        
mn      : KIOXIA-EXCERIA PLUS G2 SSD              
fr      : ECFA13.3
rab     : 1
ieee    : 8ce38e
cmic    : 0
mdts    : 9
cntlid  : 1
ver     : 10300
rtd3r   : 989680
rtd3e   : 989680
oaes    : 0x200
oacs    : 0x17
acl     : 3
aerl    : 3
frmw    : 0x12
lpa     : 0xa
elpe    : 62
npss    : 4
avscc   : 0x1
apsta   : 0x1
wctemp  : 345
cctemp  : 363
mtfa    : 100
hmpre   : 0
hmmin   : 0
tnvmcap : 500107862016
unvmcap : 0
rpmbs   : 0
sqes    : 0x66
cqes    : 0x44
nn      : 1
oncs    : 0x5f
fuses   : 0
fna     : 0
vwc     : 0x1
awun    : 255
awupf   : 0
nvscc   : 1
acwu    : 0
sgls    : 0
ps    0 : mp:10.73W operational enlat:1 exlat:1 rrt:0 rrl:0
          rwt:0 rwl:0 idle_power:- active_power:-
ps    1 : mp:7.69W operational enlat:1 exlat:1 rrt:1 rrl:1
          rwt:1 rwl:1 idle_power:- active_power:-
ps    2 : mp:6.18W operational enlat:1 exlat:1 rrt:2 rrl:2
          rwt:2 rwl:2 idle_power:- active_power:-
ps    3 : mp:0.0500W non-operational enlat:7000 exlat:5000 rrt:3 rrl:3
          rwt:3 rwl:3 idle_power:- active_power:-
ps    4 : mp:0.0050W non-operational enlat:13000 exlat:36000 rrt:4 rrl:4
          rwt:4 rwl:4 idle_power:- active_power:-
```

what information else do I need to provide to support these SSDs? 
Thanks.

for more information about these SSDs, here is the link

https://www.kioxia.com/ja-jp/personal/ssd/exceria-plus-g2-nvme-ssd.html

Sorry for the Japanese, these product cannot be found when switch language to english page.

**Comment by 007revad** [comment]
I've just released an new version that includes the KIOXIA vid
https://github.com/007revad/Synology_HDD_db/releases/tag/v3.2.69

**Comment by WanpengQian** [comment]
after execute the latest script. still cannot add M2 ssd as pool

```
root@DNAS:/volume2/Share/Script/Synology_HDD_db-3.3.70# ./syno_hdd_db.sh 
Synology_HDD_db v3.3.70
DS1821+ DSM 7.2.1-69057-3 
StorageManager 1.0.0-0017

Using options: 
Running from: /volume2/Share/Script/Synology_HDD_db-3.3.70/syno_hdd_db.sh
./syno_hdd_db.sh: line 314: lsblk: command not found
Added KIOXIA to pci_vendor_ids

HDD/SSD models found: 1
MN06ACA10T,0603

M.2 drive models found: 2
KIOXIA-EXCERIA PLUS G2 SSD,ECFA11.3
KIOXIA-EXCERIA PLUS G2 SSD,ECFA13.3

No M.2 PCIe cards found

No Expansion Units found

MN06ACA10T already exists in ds1821+_host_v7.db
Updated KIOXIA-EXCERIA PLUS G2 SSD to ds1821+_host_v7.db
Updated KIOXIA-EXCERIA PLUS G2 SSD to ds1821+_host_v7.db

Support disk compatibility already enabled.

Re-enabled support memory compatibility.

NVMe support already enabled.

M.2 volume support already enabled.

Re-enabled drive db auto updates.

DSM successfully checked disk compatibility.

You may need to reboot the Synology to see the changes.
```

![Snipaste_2023-12-18_18-15-50](https://github.com/007revad/Synology_HDD_db/assets/6359418/15e23b07-89dd-405b-b6fe-17e086ea6509)

![Snipaste_2023-12-18_18-15-59](https://github.com/007revad/Synology_HDD_db/assets/6359418/ec580037-23b8-434f-849b-278d3c811707)

**Comment by WanpengQian** [comment]
After I manual update HDD db from UI, it can create pool Now.
Thanks!!!
